she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('edit/<int:pk>/', views.EditStoryView.as_view(), name='editStory'),
    path('delete/<int:pk>/', views.DeleteStoryView.as_view(), name='deleteStory'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('news.urls')),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')), 
    path('users/', include('django.contrib.auth.urls')),
] 

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, UserHomePageView, ProfilePageView

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(),
    name = 'createAccount'),
    path('user-homepage/', UserHomePageView.as_view(),
    name = 'userHomePage'),
    path('profile/<int:pk>', ProfilePageView.as_view(), name="profile-page"),
]

she_codes_news/news/models.py
from http.client import MULTIPLE_CHOICES
from django.contrib.auth import get_user_model
from users.models import CustomUser
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name

class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
        )
    pub_date = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    category = models.ForeignKey(
        Category, 
        on_delete=models.SET_NULL,
        related_name = "stories",
        null = True,
        blank = True
        )
    image = models.URLField(blank=True, null=True)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser (AbstractUser):
    github_url = models.URLField(blank=True, null=True)
    linkedin_url = models.URLField(blank=True, null=True)
    profile_pic = models.URLField(blank=True, null=True)
    bio = models.TextField(max_length=2000, blank=True, null=True)
    
    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django.forms import ModelForm
from .models import NewsStory

category_options = [("Python","Python"), ("Django","Django"),("HTML","HTML"), ("CSS","CSS"), ("JavaScript","JavaScript"), ("React","React"), ("General","General"), ("Career","Career")]

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ["title", "category", "content", "image"]
    

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']


class UserProfileForm(forms.ModelForm):
    
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'profile_pic', 'github_url', 'linkedin_url', 'bio' ]

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm



class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all()[:4]
        context['all_stories'] = NewsStory.objects.all()
        return context



class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'


class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)



class EditStoryView(generic.UpdateView):
    model = NewsStory
    fields = ['title', 'category', 'image', 'content']
    context_object_name = 'editStoryForm'
    template_name = 'news/edit_story.html'
    success_url = reverse_lazy('news:index')



class DeleteStoryView(generic.DeleteView):
    model = NewsStory
    template_name = 'news/delete_story.html'
    success_url = reverse_lazy('news:index')

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm, UserProfileForm

# Create your views here.
class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

class UserHomePageView(UpdateView):
    model = CustomUser
    form_class = UserProfileForm
    success_url = reverse_lazy('news:index')
    
    template_name = 'users/userHomePage.html'

    def get_object(self, queryset=None):
        return self.request.user

class ProfilePageView(DetailView): 
    model = CustomUser
    template_name = "users/profile.html"
    context_object_name = 'profilePage'

she_codes_news/news/templates/news/createStory.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %} 

{% block content %}
<section class="paper">

    <div class='pin'>
        <img src="{% static 'news/images/SheCodesPin.png' %}">
    </div>

    <h2>Create A New Story</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit">
    </form>

</section>

{% endblock %}

she_codes_news/news/templates/news/delete_story.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %} 

{% block content %}
<section class='paper'>
    
    <div class='pin'>
        <img src="{% static 'news/images/SheCodesPin.png' %}">
    </div>

    <h2>Delete Story</h2>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure that you want to delete this story?</p>
        <input type="submit" value="submit">
    </form>
</section>

{% endblock %}

she_codes_news/news/templates/news/edit_story.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %} 

{% block content %}
<section class='paper'>

    <div class='pin'>
        <img src="{% static 'news/images/SheCodesPin.png' %}">
    </div>

    <h2>Update Story</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit">
    </form>
    
</section>

{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

    <div id="all-stories">
        {% if all_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %} 

{% block content %}
<div id="story-wrapper">

    <div class='pin'>
        <img src="{% static 'news/images/SheCodesPin.png' %}">
    </div>

    <section class="actual-story">
        <h2>{{ story.title }}</h2>
        <a href="{% url 'users:profile-page' story.author.id %}">{{ story.author }}</a>
        <h4>{{ story.category }}</h4>
        {% if story.author == request.user %}
            <div class="edit-card">
                <a href="{% url 'news:editStory' story.pk %}">Update Story</a>
                <a href="{% url 'news:deleteStory' story.pk %}">Delete Story</a>
            </div>
        {% endif %}

        <div id="story-content">
            {% if story.image %}
                <img src="{{ story.image }}">
            {% else %}
                <img src="https://picsum.photos/600">
            {% endif %}
            {{ story.content|linebreaks }}
        </div>
    </section>

</div>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %} 

<div class="story-card" id="story-card-{{ position }}">

    <div class='pin'>
        <img src="{% static 'news/images/SheCodesPin.png' %}">
    </div>

    <section class="story-preview">
        <a href="{% url 'news:story' story.id %}">
            {% if story.image %}
                <img src="{{ story.image }}">
            {% else %}
                <img src="https://picsum.photos/600">
            {% endif %}
            <div class="story-card-text">
                <h3>{{ story.title }}</h3>
                <a href="{% url 'users:profile-page' story.author.id %}">{{ story.author }}</a>
                <h4>{{ story.pub_date }}</h4>
                <h4>{{ story.category }}</h4>
            </div>
            {% if story.author == request.user %}
                <div class="edit-card">
                    <a href="{% url 'news:deleteStory' story.pk %}">Delete Story</a>
                    <a href="{% url 'news:editStory' story.pk %}">Update Story</a>
                </div>
            {% endif %}
        </a>
    </section>

</div>

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <link rel="icon" type="image/x-icon" href="{% static '/favicon.ico' %}">
        <meta name="description" content="Suelee's Django Project">
        <meta name="author" content="Suelee Christie">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;900&family=Playfair+Display:ital,wght@0,800;1,400&family=Praise&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She <span class="codes">{Codes}</span> Bulletin Board</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
        {% block content %}{% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav class='nav'>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
        <a href="{% url 'news:newStory' %}">Write New Story</a>
        <a href="{% url 'users:userHomePage' %}">{{ user.username }}</a>
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'users/styles.css' %}">
{% endblock %}

{% block content %}

<section class="paper">

    <div class='pin'>
        <img src="{% static 'news/images/SheCodesPin.png' %}">
    </div>

    <div class='create-account'>
        <h2>Create Account</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create Account</button>
        </form>
    </div>

</section>
{% endblock %}

she_codes_news/users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'users/styles.css' %}">
{% endblock %}

{% block content %}

<section class="paper">

    <div class='pin'>
        <img src="{% static 'news/images/SheCodesPin.png' %}">
    </div>

    <div class='profile-info'>
        <h1> {{ profilePage.first_name }} {{ profilePage.last_name }} </h1>
        {% if profilePage.profile_pic %}
            <img src="{{ profilePage.profile_pic }}">
        {% endif %}
        {% if profilePage.github_url %}
        <a href="{{ profilePage.github_url }}">{{ profilePage.github_url }}</a>
        {% endif %}
        {% if profilePage.linkedin_url %}
        <a href="{{ profilePage.linkedin_url }}" >{{ profilePage.linkedin_url }}</a>
        {% endif %}
        {% if profilePage.bio %}
        <p> {{ profilePage.bio }} </p>
        {% endif %}
    </div>

</section>

{% endblock %}

she_codes_news/users/templates/users/userHomePage.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'users/styles.css' %}">
{% endblock %}

{% block content %}

<section class="paper">

    <div class='pin'>
        <img src="{% static 'news/images/SheCodesPin.png' %}">
    </div>
    
    <h1 class="welcome">Welcome {{ user.username }}!</h1>

    <div class="edit-profile">
        <h2>Edit Profile</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="submit">
        </form>
    </div>
</section>

{% endblock %}